# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from protos import read_text_file_pb2 as protos_dot_read__text__file__pb2


class FileReaderStub(object):
    """This is my service. A class that contain multiple rpc functions.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.read_secret_file = channel.unary_unary(
                '/protos.FileReader/read_secret_file',
                request_serializer=protos_dot_read__text__file__pb2.read_secret_request.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
                )


class FileReaderServicer(object):
    """This is my service. A class that contain multiple rpc functions.
    """

    def read_secret_file(self, request, context):
        """This RPC will appear as a function on my server.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileReaderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'read_secret_file': grpc.unary_unary_rpc_method_handler(
                    servicer.read_secret_file,
                    request_deserializer=protos_dot_read__text__file__pb2.read_secret_request.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protos.FileReader', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FileReader(object):
    """This is my service. A class that contain multiple rpc functions.
    """

    @staticmethod
    def read_secret_file(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.FileReader/read_secret_file',
            protos_dot_read__text__file__pb2.read_secret_request.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
