# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/read_text_file.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/read_text_file.proto',
  package='protos',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1bprotos/read_text_file.proto\x12\x06protos\x1a\x1egoogle/protobuf/wrappers.proto\"0\n\x13read_secret_request\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03pin\x18\x02 \x01(\x05\x32]\n\nFileReader\x12O\n\x10read_secret_file\x12\x1b.protos.read_secret_request\x1a\x1c.google.protobuf.StringValue\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,])




_READ_SECRET_REQUEST = _descriptor.Descriptor(
  name='read_secret_request',
  full_name='protos.read_secret_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='protos.read_secret_request.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pin', full_name='protos.read_secret_request.pin', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=119,
)

DESCRIPTOR.message_types_by_name['read_secret_request'] = _READ_SECRET_REQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

read_secret_request = _reflection.GeneratedProtocolMessageType('read_secret_request', (_message.Message,), {
  'DESCRIPTOR' : _READ_SECRET_REQUEST,
  '__module__' : 'protos.read_text_file_pb2'
  # @@protoc_insertion_point(class_scope:protos.read_secret_request)
  })
_sym_db.RegisterMessage(read_secret_request)



_FILEREADER = _descriptor.ServiceDescriptor(
  name='FileReader',
  full_name='protos.FileReader',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=121,
  serialized_end=214,
  methods=[
  _descriptor.MethodDescriptor(
    name='read_secret_file',
    full_name='protos.FileReader.read_secret_file',
    index=0,
    containing_service=None,
    input_type=_READ_SECRET_REQUEST,
    output_type=google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FILEREADER)

DESCRIPTOR.services_by_name['FileReader'] = _FILEREADER

# @@protoc_insertion_point(module_scope)
